# Required
appID: "APP ID HERE"

# Optional if you change contact.md and privacy.md
email: hello@example.com

# Mainly used for OG image. If not set, the OG image may be unavailable.
# site-url: https://example.com

# Optional Overrides
# title: CoolApp
# headline: Up your cool with CoolApp
# subheadline: CoolApp helps you increase your coolness-factor by at least 19 percent. Some users even report a slight increase in their swagger.
# accent-color: "#ec5e3a"
# accent-color-dark: "#ec5e3a"
# developer: John Appleseed
# developer-link: https://example.com
